<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo">
            <img src="{{asset('admin/assets/images/favicon.png')}}" alt="logo" style="width: 70px; height: 70px;" />
          </a>
      <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="{{asset('admin/assets/images/logo-mini.svg')}}" alt="logo" /></a>
    </div>
    <ul class="nav">
      <li class="nav-item profile">
        <div class="profile-desc">
          <div class="profile-pic">
            <div class="count-indicator">
              <img class="img-xs rounded-circle " src="{{asset('admin/assets/images/faces/face15.jpg')}}" alt="">
              <span class="count bg-success"></span>
            </div>
            <a href="https://www.facebook.com/profile.php?id=100074969645385" class="profile-link">
                <div class="profile-name">
                    <h5 class="mb-0 font-weight-normal">Chan Thar Htoo</h5>
                    <span>Administrator</span>
                </div>
            </a>

          </div>
          <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
          <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
          </div>
        </div>
      </li>
      <li class="nav-item nav-category">
        <span class="nav-link">Navigation</span>
      </li>
      <li class="nav-item menu-items">
        <a class="nav-link" href="{{'/redirect'}}">
          <span class="menu-icon">
            <i class="mdi mdi-speedometer"></i>
          </span>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Products</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-basic">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{{url('/view_product')}}">Add Products</a></li>

            <li class="nav-item"> <a class="nav-link" href="{{url('/show_product')}}">Show Product</a></li>

          </ul>
        </div>
      </li>
      <li class="nav-item menu-items">
            <!-- user clicks on this link, it will navigate to the URL generated by the url helper for the path 'view_catagory' -->
            <a class="nav-link" href="{{url('view_catagory')}}">
            <span class="menu-icon">
                <i class="mdi mdi-playlist-play"></i>
            </span>
            <span class="menu-title">Catagory</span>
            </a>
      </li>

      <li class="nav-item menu-items">
            <!-- user clicks on this link, it will navigate to the URL generated by the url helper for the path 'view_catagory' -->
            <a class="nav-link" href="{{url('order')}}">
            <span class="menu-icon">
                <i class="fa-brands fa-jedi-order" style="color: #d42548;"></i>
            </span>
            <span class="menu-title">Order</span>
            </a>
      </li>
    </ul>
  </nav>
